/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 static/models/jerry_robot-web.glb -o src/components/ThreeModels/Jerry.jsx 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Jerry(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/jerry_robot-web.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Пустышка" position={[3.933, 0.01, 0.143]} scale={[1, 0.83, 1]} />
        <lineSegments name="ТраекторияNurbs" geometry={nodes.ТраекторияNurbs.geometry} material={materials.Материал} position={[3.933, -0.064, 0.152]} rotation={[0, Math.PI / 2, 0]} />
        <mesh name="Цилиндр001" geometry={nodes.Цилиндр001.geometry} material={materials.Материал} position={[3.933, 0, -1.595]} rotation={[0, 0, -Math.PI / 2]} scale={[1.29, 0.068, 1.29]} />
        <group name="Цилиндр003" position={[3.933, 0, -1.595]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Цилиндр004_1" geometry={nodes.Цилиндр004_1.geometry} material={materials.Материал} />
          <mesh name="Цилиндр004_2" geometry={nodes.Цилиндр004_2.geometry} material={materials['Материал.004']} />
        </group>
        <mesh name="Куб001" geometry={nodes.Куб001.geometry} material={materials.Материал} position={[3.933, 0.01, -58.811]} />
        <mesh name="Куб002" geometry={nodes.Куб002.geometry} material={materials['Материал.003']} position={[0.322, 0.496, 0.064]} />
        <mesh name="Куб003" geometry={nodes.Куб003.geometry} material={materials.Материал} position={[0.322, 0, -1.595]} />
        <mesh name="Куб004" geometry={nodes.Куб004.geometry} material={materials.Материал} position={[0.322, 0, 2.05]} scale={[3.464, 0.437, 0.437]} />
        <mesh name="Куб005" geometry={nodes.Куб005.geometry} material={materials['Материал.001']} position={[0.322, 1.485, 1.684]} />
        <mesh name="Куб006" geometry={nodes.Куб006.geometry} material={materials.Материал} position={[0.322, 0.752, 1.684]} scale={[3.035, 0.047, 1]} />
        <mesh name="Цилиндр004" geometry={nodes.Цилиндр004.geometry} material={materials.Материал} position={[3.088, 1.485, 2.413]} scale={[0.207, 1, 0.207]} />
        <mesh name="Куб007" geometry={nodes.Куб007.geometry} material={materials['Материал.001']} position={[0.322, 1.683, 0.414]} rotation={[-0.087, 0, 0]} scale={[2.718, 0.047, 1]} />
        <mesh name="Куб008" geometry={nodes.Куб008.geometry} material={materials['Материал.004']} position={[-2.531, 2.208, -2.094]} rotation={[0, 0, Math.PI]} scale={1.164} />
        <group name="Цилиндр006" position={[-1.138, 2.208, -2.467]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={0.374}>
          <mesh name="Цилиндр012_1" geometry={nodes.Цилиндр012_1.geometry} material={materials.Материал} />
          <mesh name="Цилиндр012_2" geometry={nodes.Цилиндр012_2.geometry} material={materials['Материал.009']} />
        </group>
        <group name="Цилиндр007" position={[-2.031, 2.208, -2.42]} rotation={[-Math.PI / 2, 0, Math.PI]}>
          <mesh name="Цилиндр013_1" geometry={nodes.Цилиндр013_1.geometry} material={materials.Материал} />
          <mesh name="Цилиндр013_2" geometry={nodes.Цилиндр013_2.geometry} material={materials['Материал.009']} />
        </group>
        <mesh name="Цилиндр008" geometry={nodes.Цилиндр008.geometry} material={materials['Материал.004']} position={[-1.825, 0.62, -2.169]} />
        <mesh name="ТраекторияNurbs001" geometry={nodes.ТраекторияNurbs001.geometry} material={materials['Материал.007']} position={[-1.584, 4.393, -2.229]} rotation={[0, 0, Math.PI / 2]} />
        <group name="Куб010" position={[2.456, 2.262, -0.492]} scale={0.717}>
          <mesh name="Куб013_1" geometry={nodes.Куб013_1.geometry} material={materials['Материал.002']} />
          <mesh name="Куб013_2" geometry={nodes.Куб013_2.geometry} material={materials.Материал} />
        </group>
        <mesh name="Куб011" geometry={nodes.Куб011.geometry} material={materials.Материал} position={[3.446, 1.864, 1.785]} rotation={[0, 0, -Math.PI / 9]} scale={[0.024, 0.327, 0.247]} />
        <mesh name="ТраекторияNurbs002" geometry={nodes.ТраекторияNurbs002.geometry} material={materials.Материал} position={[3.446, 1.864, 1.785]} />
        <mesh name="ТраекторияNurbs003" geometry={nodes.ТраекторияNurbs003.geometry} material={materials['Материал.002']} position={[3.691, 1.864, 1.785]} />
        <mesh name="ТраекторияNurbs004" geometry={nodes.ТраекторияNurbs004.geometry} material={materials.Материал} position={[3.935, 1.864, 1.785]} />
        <mesh name="ТраекторияNurbs005" geometry={nodes.ТраекторияNurbs005.geometry} material={materials['Материал.004']} position={[4.667, 3.757, 3.544]} />
        <mesh name="ТраекторияNurbs006" geometry={nodes.ТраекторияNurbs006.geometry} material={materials['Материал.002']} position={[5.087, 3.757, 3.544]} />
        <mesh name="ТраекторияNurbs007" geometry={nodes.ТраекторияNurbs007.geometry} material={materials['Материал.001']} position={[1.395, 2.435, 0.789]} rotation={[1.168, -0.872, 1.063]} />
        <mesh name="ТраекторияNurbs008" geometry={nodes.ТраекторияNurbs008.geometry} material={materials.Материал} position={[1.739, 2.435, 0.789]} rotation={[1.168, -0.872, 1.063]} />
        <mesh name="ТраекторияNurbs009" geometry={nodes.ТраекторияNurbs009.geometry} material={materials['Материал.005']} position={[1.739, 2.435, 1.056]} rotation={[1.168, -0.872, 1.063]} />
        <mesh name="Куб" geometry={nodes.Куб.geometry} material={materials.Материал} position={[0.322, 0.002, 0.064]} scale={[1.926, 1, 1]} />
        <mesh name="Окружность" geometry={nodes.Окружность.geometry} material={materials['Материал.004']} position={[0.441, -1.325, 0.5]} scale={6.471} />
        <group name="Куб012" position={[-1.379, 1.666, 2.221]}>
          <mesh name="Куб001_1" geometry={nodes.Куб001_1.geometry} material={materials['Материал.004']} />
          <mesh name="Куб001_2" geometry={nodes.Куб001_2.geometry} material={materials.Материал} />
        </group>
        <group name="Куб013" position={[2.576, 1.613, 2.413]} scale={[0.447, 0.606, 0.586]}>
          <mesh name="Куб002_1" geometry={nodes.Куб002_1.geometry} material={materials['Материал.004']} />
          <mesh name="Куб002_2" geometry={nodes.Куб002_2.geometry} material={materials.Материал} />
        </group>
        <group name="Куб014" position={[1.575, 1.613, 2.413]} scale={[0.447, 0.606, 0.586]}>
          <mesh name="Куб005_1" geometry={nodes.Куб005_1.geometry} material={materials['Материал.004']} />
          <mesh name="Куб005_2" geometry={nodes.Куб005_2.geometry} material={materials.Материал} />
        </group>
        <group name="Куб009" position={[-0.939, 1.596, -0.575]}>
          <mesh name="Куб017_1" geometry={nodes.Куб017_1.geometry} material={materials['Материал.005']} />
          <mesh name="Куб017_2" geometry={nodes.Куб017_2.geometry} material={materials.Материал} />
          <mesh name="Куб017_3" geometry={nodes.Куб017_3.geometry} material={materials['Материал.007']} />
        </group>
        <group name="Куб015" position={[0.063, 2.018, 1.584]} scale={[0.558, 0.486, 0.558]}>
          <mesh name="Куб015_1" geometry={nodes.Куб015_1.geometry} material={materials.Материал} />
          <mesh name="Куб015_2" geometry={nodes.Куб015_2.geometry} material={materials['Материал.001']} />
        </group>
        <mesh name="Куб016" geometry={nodes.Куб016.geometry} material={materials['Материал.004']} position={[-1.754, 2.066, 1.302]} scale={0.533} />
        <group name="Куб017" position={[1.849, 1.038, 1.681]} rotation={[0, Math.PI / 2, 0]}>
          <mesh name="Куб018_1" geometry={nodes.Куб018_1.geometry} material={materials['Материал.004']} />
          <mesh name="Куб018_2" geometry={nodes.Куб018_2.geometry} material={materials['Материал.007']} />
        </group>
        <mesh name="Цилиндр009" geometry={nodes.Цилиндр009.geometry} material={materials['Материал.005']} position={[-1.633, 1.924, -1.295]} rotation={[0, 0, -Math.PI / 2]} scale={0.293} />
        <mesh name="Цилиндр010" geometry={nodes.Цилиндр010.geometry} material={materials['Материал.004']} position={[-2.233, 2.101, -1.545]} rotation={[-0.34, -0.517, -2.071]} />
        <mesh name="Куб018" geometry={nodes.Куб018.geometry} material={materials.Материал} position={[3.054, 1.782, 1.687]} scale={0.249} />
        <group name="Цилиндр005" position={[4.086, 0.01, 2.023]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.308, 1]}>
          <mesh name="Цилиндр006_1" geometry={nodes.Цилиндр006_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр006_2" geometry={nodes.Цилиндр006_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр011" position={[3.933, 0, -1.595]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.308, 1]}>
          <mesh name="Цилиндр007_1" geometry={nodes.Цилиндр007_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр007_2" geometry={nodes.Цилиндр007_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр012" position={[-3.628, 0.036, -1.583]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.308, 1]}>
          <mesh name="Цилиндр008_1" geometry={nodes.Цилиндр008_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр008_2" geometry={nodes.Цилиндр008_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр013" position={[-3.485, 0.005, 2.037]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 0.308, 1]}>
          <mesh name="Цилиндр010_1" geometry={nodes.Цилиндр010_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр010_2" geometry={nodes.Цилиндр010_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр014" position={[4.086, 0.016, 2.008]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Цилиндр011_1" geometry={nodes.Цилиндр011_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр011_2" geometry={nodes.Цилиндр011_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр015" position={[3.933, 0, -1.595]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Цилиндр015_1" geometry={nodes.Цилиндр015_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр015_2" geometry={nodes.Цилиндр015_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр016" position={[-3.442, 0, -1.606]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Цилиндр016_1" geometry={nodes.Цилиндр016_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр016_2" geometry={nodes.Цилиндр016_2.geometry} material={materials.Материал} />
        </group>
        <group name="Цилиндр017" position={[-3.443, 0.006, 2.038]} rotation={[0, 0, -Math.PI / 2]}>
          <mesh name="Цилиндр017_1" geometry={nodes.Цилиндр017_1.geometry} material={materials.Материал} />
          <lineSegments name="Цилиндр017_2" geometry={nodes.Цилиндр017_2.geometry} material={materials.Материал} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/jerry_robot-web.glb')
